/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lastorderapp;

/**
 *
 * @author doomsayer
 */
public class DepartmentPanel extends javax.swing.JPanel {

    static int selectedDepartmentRow = -1;
    
    /**
     * Creates new form DepartmentPanel
     */
    public DepartmentPanel() {
        initComponents();
        viewDepartmentWorkers.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        LastOrderAppPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("LastOrderAppPU").createEntityManager();
        departmentsQuery = java.beans.Beans.isDesignTime() ? null : LastOrderAppPUEntityManager.createQuery("SELECT d FROM Departments d ORDER BY d.departmentId");
        departmentsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : departmentsQuery.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addNewDepartmentButton = new javax.swing.JButton();
        viewDepartmentWorkers = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 10, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0};
        setLayout(layout);

        jScrollPane1.setEnabled(false);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 200));

        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, departmentsList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${departmentId}"));
        columnBinding.setColumnName("Department Id");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${departmentName}"));
        columnBinding.setColumnName("Department Name");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        add(jScrollPane1, gridBagConstraints);

        addNewDepartmentButton.setText("Add new department");
        addNewDepartmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewDepartmentButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(addNewDepartmentButton, gridBagConstraints);

        viewDepartmentWorkers.setText("View department workers");
        viewDepartmentWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDepartmentWorkersActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(viewDepartmentWorkers, gridBagConstraints);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void viewDepartmentWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDepartmentWorkersActionPerformed
        // TODO add your handling code here:
        this.getParent().getParent().getParent().getParent().getParent().setVisible(false);
        viewDepartmentWorkersFrame viewDepartmentWorkersFrame = new viewDepartmentWorkersFrame();
        viewDepartmentWorkersFrame.setVisible(true);
        
        
    }//GEN-LAST:event_viewDepartmentWorkersActionPerformed

    private void addNewDepartmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewDepartmentButtonActionPerformed
        // TODO add your handling code here:
        AddNewDepartmentFrame AddNewDepartmentFrame = new AddNewDepartmentFrame();
        AddNewDepartmentFrame.setVisible(true);
        this.getParent().getParent().getParent().getParent().getParent().setVisible(false);
    }//GEN-LAST:event_addNewDepartmentButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        selectedDepartmentRow = jTable1.getSelectedRow();
        if (selectedDepartmentRow == -1) {
            viewDepartmentWorkers.setEnabled(false);
        } else{
            viewDepartmentWorkers.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        selectedDepartmentRow = jTable1.getSelectedRow();
        if (selectedDepartmentRow == -1) {
            viewDepartmentWorkers.setEnabled(false);
        } else{
            viewDepartmentWorkers.setEnabled(true);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager LastOrderAppPUEntityManager;
    private javax.swing.JButton addNewDepartmentButton;
    private java.util.List<lastorderapp.database.Departments> departmentsList;
    private javax.persistence.Query departmentsQuery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton viewDepartmentWorkers;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
