/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lastorderapp;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author doomsayer
 */
public class OrderPanel extends javax.swing.JPanel {

    public static int selectedColumn;
    /**
     * Creates new form OrderPanel
     */
    public OrderPanel() {
        initComponents();
        selectedColumn = jTable1.getSelectedRow();
        System.out.println(selectedColumn);
        if (selectedColumn == -1){
            viewButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        LastOrderAppPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("LastOrderAppPU").createEntityManager();
        ordersQuery = java.beans.Beans.isDesignTime() ? null : LastOrderAppPUEntityManager.createQuery("SELECT o FROM Orders o ORDER BY o.id");
        ordersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ordersQuery.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addNewWorkerButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 10, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0};
        setLayout(layout);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 200));

        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, ordersList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${workType}"));
        columnBinding.setColumnName("Work Type");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${departmentId}"));
        columnBinding.setColumnName("Department Id");
        columnBinding.setColumnClass(lastorderapp.database.Departments.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${roomId}"));
        columnBinding.setColumnName("Room Id");
        columnBinding.setColumnClass(lastorderapp.database.Rooms.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${issuedJobId}"));
        columnBinding.setColumnName("Issued Job Id");
        columnBinding.setColumnClass(lastorderapp.database.Workers.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${acceptedJobId}"));
        columnBinding.setColumnName("Accepted Job Id");
        columnBinding.setColumnClass(lastorderapp.database.Workers.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${startDate}"));
        columnBinding.setColumnName("Start Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${endDate}"));
        columnBinding.setColumnName("End Date");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 7;
        add(jScrollPane1, gridBagConstraints);

        addNewWorkerButton.setText("Add new order");
        addNewWorkerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewWorkerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(addNewWorkerButton, gridBagConstraints);

        viewButton.setText("View order workers and tools");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        add(viewButton, gridBagConstraints);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewWorkerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewWorkerButtonActionPerformed
        // TODO add your handling code here:
        AddNewOrderFrame AddNewOrderFrame = new AddNewOrderFrame();
        AddNewOrderFrame.setVisible(true);
        this.getParent().getParent().getParent().getParent().getParent().setVisible(false);
    }//GEN-LAST:event_addNewWorkerButtonActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        selectedColumn = jTable1.getSelectedRow();
        System.out.println(selectedColumn);
        if (selectedColumn == -1){
            viewButton.setEnabled(false);
        } else{
            viewButton.setEnabled(true);
        }
    }//GEN-LAST:event_formMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        selectedColumn = jTable1.getSelectedRow();
        System.out.println(selectedColumn);
        if (selectedColumn == -1){
            viewButton.setEnabled(false);
        } else{
            viewButton.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        viewOrderFrame viewOrderFrame;
        try {
            viewOrderFrame = new viewOrderFrame();
            viewOrderFrame.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(OrderPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.getParent().getParent().getParent().getParent().getParent().setVisible(false);
    }//GEN-LAST:event_viewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager LastOrderAppPUEntityManager;
    private javax.swing.JButton addNewWorkerButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<lastorderapp.database.Orders> ordersList;
    private javax.persistence.Query ordersQuery;
    private javax.swing.JButton viewButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
