/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lastorderapp;

/**
 *
 * @author doomsayer
 */
public class RoomsPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomsPanel
     */
    public RoomsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        LastOrderAppPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("LastOrderAppPU").createEntityManager();
        roomsQuery = java.beans.Beans.isDesignTime() ? null : LastOrderAppPUEntityManager.createQuery("SELECT r FROM Rooms r ORDER BY r.roomId");
        roomsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : roomsQuery.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();
        addNewRoomButton = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 10, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0};
        setLayout(layout);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 200));

        roomTable.setPreferredSize(new java.awt.Dimension(600, 600));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, roomsList, roomTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${roomId}"));
        columnBinding.setColumnName("Room Id");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${roomName}"));
        columnBinding.setColumnName("Room Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${roomAdress}"));
        columnBinding.setColumnName("Room Adress");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(roomTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        add(jScrollPane1, gridBagConstraints);

        addNewRoomButton.setText("Add new room");
        addNewRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRoomButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(addNewRoomButton, gridBagConstraints);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRoomButtonActionPerformed
        // TODO add your handling code here:
        AddNewRoomFrame AddNewRoomFrame = new AddNewRoomFrame();
        AddNewRoomFrame.setVisible(true);
        this.getParent().getParent().getParent().getParent().getParent().setVisible(false);
    }//GEN-LAST:event_addNewRoomButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager LastOrderAppPUEntityManager;
    private javax.swing.JButton addNewRoomButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable roomTable;
    private java.util.List<lastorderapp.database.Rooms> roomsList;
    private javax.persistence.Query roomsQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
