/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lastorderapp;

/**
 *
 * @author doomsayer
 */
public class WorkerPanel extends javax.swing.JPanel {

    static int selectedWorkerRow = -1;
    
    
    /**
     * Creates new form WorkerPanel
     */
    public WorkerPanel() {
        initComponents();
        viewWorkerOrdersButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        LastOrderAppPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("LastOrderAppPU").createEntityManager();
        workersQuery = java.beans.Beans.isDesignTime() ? null : LastOrderAppPUEntityManager.createQuery("SELECT w FROM Workers w order by w.workerId");
        workersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : workersQuery.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        workersTable = new javax.swing.JTable();
        addNewWorkerButton = new javax.swing.JButton();
        viewWorkerOrdersButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 10, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        setLayout(layout);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 200));

        workersTable.setMinimumSize(new java.awt.Dimension(400, 400));
        workersTable.setPreferredSize(new java.awt.Dimension(400, 400));
        workersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, workersList, workersTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${workerId}"));
        columnBinding.setColumnName("Worker Id");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${workerName}"));
        columnBinding.setColumnName("Worker Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${workerPosition}"));
        columnBinding.setColumnName("Worker Position");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${workerDepartment}"));
        columnBinding.setColumnName("Worker Department");
        columnBinding.setColumnClass(lastorderapp.database.Departments.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        workersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(workersTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 9;
        add(jScrollPane1, gridBagConstraints);

        addNewWorkerButton.setText("Add new worker");
        addNewWorkerButton.setMaximumSize(new java.awt.Dimension(179, 23));
        addNewWorkerButton.setMinimumSize(new java.awt.Dimension(179, 23));
        addNewWorkerButton.setPreferredSize(new java.awt.Dimension(179, 23));
        addNewWorkerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewWorkerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(addNewWorkerButton, gridBagConstraints);

        viewWorkerOrdersButton.setText("View worker's orders");
        viewWorkerOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewWorkerOrdersButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(viewWorkerOrdersButton, gridBagConstraints);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewWorkerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewWorkerButtonActionPerformed
        // TODO add your handling code here:
        AddNewWorker AddNewWorker = new AddNewWorker();
        AddNewWorker.setVisible(true);
        this.getParent().getParent().getParent().getParent().getParent().setVisible(false);
    }//GEN-LAST:event_addNewWorkerButtonActionPerformed

    private void workersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workersTableMouseClicked
        // TODO add your handling code here:
        selectedWorkerRow = workersTable.getSelectedRow();
        if (selectedWorkerRow == -1) {
            viewWorkerOrdersButton.setEnabled(false);
        }else viewWorkerOrdersButton.setEnabled(true);
        
    }//GEN-LAST:event_workersTableMouseClicked

    private void viewWorkerOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewWorkerOrdersButtonActionPerformed
        // TODO add your handling code here:
        viewWorkerOrdersFrame viewWorkerOrdersFrame = new viewWorkerOrdersFrame();
        viewWorkerOrdersFrame.setVisible(true);
        this.getParent().getParent().getParent().getParent().getParent().setVisible(false);
        
    }//GEN-LAST:event_viewWorkerOrdersButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager LastOrderAppPUEntityManager;
    private javax.swing.JButton addNewWorkerButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewWorkerOrdersButton;
    private java.util.List<lastorderapp.database.Workers> workersList;
    private javax.persistence.Query workersQuery;
    private javax.swing.JTable workersTable;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
